"""
The letter-scoring system of Example 1 bis, where the LLM no longer outputs a score, but fills in a CHECKLIST of boolean criteria:
the score is then computed by code, from the checklist, so it is reproducible and explainable.

Run with: poetry run python -m snippets -l prompting -x 1 mario-rossi
(the letter can be given as a candidate's ID, or as a path, e.g. data/letter-mario-rossi.txt)
Configure via env vars: OPENAI_BASE_URL, OPENAI_API_KEY, OPENAI_MODEL.
"""
from pydantic import BaseModel, Field
# same LLM, prompt, and extracted information as Example 1 bis: only the scoring changes
from snippets.lecture_prompting.example1bis.letter_scoring_langchain import llm, model, prompt, ApplicantInfo, AuthorInfo


# step 2-3: the scoring recipe of Example 1 bis, turned into a checklist, i.e. one boolean field per criterion
# (phrased so that True is always GOOD, and descriptions tell the LLM exactly what to check)
class Checklist(BaseModel):
    """Criteria for assessing a recommendation letter: set each one to true only if the letter clearly satisfies it."""

    clear_acquaintance: bool = Field(description="The letter clearly states how, where, and for how long the author knows the applicant.")
    storytelling: bool = Field(description="The letter tells concrete stories or episodes about the applicant, rather than just listing adjectives.")
    concrete_skills: bool = Field(description="The skills attributed to the applicant are specific and supported by concrete examples.")
    concrete_strengths: bool = Field(description="The letter mentions strengths of the applicant (other than skills), supported by concrete examples.")
    no_weaknesses: bool = Field(description="The author does NOT mention weaknesses of the applicant, neither explicitly nor implicitly (e.g. 'needs supervision').")
    tailored: bool = Field(description="The letter is tailored for the specific PhD programme the applicant is applying for.")


class LetterInfo(BaseModel):
    applicant: ApplicantInfo = Field(description="Information about the person the letter is about, i.e., the one applying for the PhD programme.")
    author: AuthorInfo = Field(description="Information about the person who wrote the letter, i.e., the one recommending the applicant for the PhD programme.")
    application_for: str = Field(description="The PhD programme for which the applicant is applying.")
    checklist: Checklist = Field(description="Assessment of the letter, criterion by criterion.")
    # no `score` field here: the LLM does not compute it anymore!

    # step 5: the scoring algorithm, as code (a property: computed from the other fields, never generated by the LLM)
    @property
    def missing_fields(self) -> list[str]:
        """The non-optional fields which the letter does not provide (e.g. empty strings or lists)."""
        required = {
            "applicant.name": self.applicant.name, "applicant.skills": self.applicant.skills, "applicant.strengths": self.applicant.strengths,
            "author.name": self.author.name, "author.affiliation": self.author.affiliation, "author.email": self.author.email,
            "application_for": self.application_for,
        }
        return [name for name, value in required.items() if not value]

    @property
    def penalties(self) -> list[str]:
        """Why points were lost: the explanation of the score."""
        failed = [name for name, satisfied in self.checklist.model_dump().items() if not satisfied]
        return failed + [f"missing {name}" for name in self.missing_fields]

    @property
    def score(self) -> int:
        """Starts from the maximum (5), and decreases by 1 per penalty, down to the minimum (0)."""
        return max(0, 5 - len(self.penalties))


scoring_chain = prompt | llm.with_structured_output(LetterInfo)  # step 4: the LLM fills in the checklist

def score_letter(letter_text: str) -> LetterInfo:
    return scoring_chain.invoke({"letter_text": letter_text})


if __name__ == "__main__":
    import sys
    import data

    print(f"Using model: {model}")

    letter_path = data.find_letter(sys.argv[1] if len(sys.argv) > 1 else input("Enter the letter to score (candidate's ID or path): "))
    if not letter_path.is_file():
        sys.exit(f"File {letter_path} is not a file.")
    letter_info = score_letter(letter_path.read_text())
    print(letter_info.model_dump_json(indent=2))
    print(f"Score: {letter_info.score}/5, penalties: {letter_info.penalties or 'none'}")  # explainable!
